---
title: "Assignment 1: Reproducibility, Workflow, Version Control"
author: "Xin Zhang"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the lessons in Environmental Data Analytics (ENV872L) on reproducibility, workflow, and version control. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
2. Use the lesson as a guide. It contains code that can be modified to complete the assignment.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
Space for your answers is provided in this document and is indicated by the ">" character.
If you need a second paragraph be sure to start the first line with ">".
You should notice that the answer is highlighted in green by RStudio. 
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
You will need to have the correct software installed to do this (see Software Installation Guide)
Press the `Knit` button in the RStudio scripting panel.
This will save the PDF output in your Assignments folder.
8. After Knitting, please submit the completed exercise (PDF file) to the dropbox in Sakai. Please add your last name into the file name (e.g., "Salk_A01_Reproducibility.pdf") prior to submission.

The completed exercise is due on Thursday, 17 January, 2018 before class begins.

## 1) Discussion Questions

### Question
Why are reproducible practices becoming the norm in data analytics?

> Answer: 1. Reproducible practices can confirm the correctness of one's data analytics results 2. Other people can learn and use the reproducible practices to do their own analytics and this interactive learning can save a lot of time, which can promote the development of data analytics.

### Question
What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took the course ENVIRON710 (R) last semester and this is my only experience with R. My previous data analytics experiences were using excel, SPSS, Origin and a little bit Matlab to do soil science research. I never used Git before. 

### Question
Are there any components of the course about which you feel confident?

> Answer: I am confident about the GLM part, because in the R course, we learnt backwards model selection for almost half of the semster. 

### Question
Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about the Github usage. I spent so much time with the Pull, Commit, and Push this time, and I think I made almost all the possible mistakes (Fortunately it worked finally). I'm worried what if this situation happens every time...(and I think it will...)  

## 2) GitHub

### Your Repository
Provide a link below to your course repository in GitHub. Make sure you have pulled all recent changes from the course repository (https://github.com/KateriSalk/Environmental_Data_Analytics) and that you have updated your course README file. 

> Answer: https://github.com/zhangxsaras/Environmental_Data_Analytics.git


